# Generated by Django 4.2 on 2023-10-09 21:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(datetime.datetime.now)]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^..-..$')]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
